"""Add check_in and check_out to Bookings

Revision ID: 43381ef59522
Revises: f3b86cfa7b4e
Create Date: 2025-07-18 10:24:22.101722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '43381ef59522'
down_revision: Union[str, Sequence[str], None] = 'f3b86cfa7b4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('check_out', sa.Integer(), nullable=True))
    op.drop_column('bookings', 'date_booked')
    op.alter_column('hotels', 'image_url',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hotels', 'image_url',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.add_column('bookings', sa.Column('date_booked', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('bookings', 'check_out')
    # ### end Alembic commands ###
