"""Make check_in and check_out non-nullable

Revision ID: 61aebd0c2c04
Revises: 43381ef59522
Create Date: 2025-07-18 10:35:57.577092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '61aebd0c2c04'
down_revision: Union[str, Sequence[str], None] = '43381ef59522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('check_in', sa.Integer(), nullable=False))
    op.alter_column('bookings', 'check_out',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'check_out',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('bookings', 'check_in')
    # ### end Alembic commands ###
