"""Add role_id to users

Revision ID: f3b86cfa7b4e
Revises: 427dba13018b
Create Date: 2025-07-14 13:29:53.064182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3b86cfa7b4e'
down_revision: Union[str, Sequence[str], None] = '427dba13018b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('password'), table_name='users')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_index(op.f('password'), 'users', ['password'], unique=True)
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###
